/* tslint:disable */
import { Assembly } from './assembly';
import { ConstructorInfo } from './constructor-info';
import { CustomAttributeData } from './custom-attribute-data';
import { GenericParameterAttributes } from './generic-parameter-attributes';
import { MemberTypes } from './member-types';
import { MethodBase } from './method-base';
import { Module } from './module';
import { RuntimeTypeHandle } from './runtime-type-handle';
import { StructLayoutAttribute } from './struct-layout-attribute';
import { TypeAttributes } from './type-attributes';
export interface Type {
  assembly?: Assembly;
  assemblyQualifiedName?: null | string;
  attributes?: TypeAttributes;
  baseType?: Type;
  containsGenericParameters?: boolean;
  customAttributes?: null | Array<CustomAttributeData>;
  declaringMethod?: MethodBase;
  declaringType?: Type;
  fullName?: null | string;
  genericParameterAttributes?: GenericParameterAttributes;
  genericParameterPosition?: number;
  genericTypeArguments?: null | Array<Type>;
  guid?: string;
  hasElementType?: boolean;
  isAbstract?: boolean;
  isAnsiClass?: boolean;
  isArray?: boolean;
  isAutoClass?: boolean;
  isAutoLayout?: boolean;
  isByRef?: boolean;
  isByRefLike?: boolean;
  isCOMObject?: boolean;
  isClass?: boolean;
  isCollectible?: boolean;
  isConstructedGenericType?: boolean;
  isContextful?: boolean;
  isEnum?: boolean;
  isExplicitLayout?: boolean;
  isGenericMethodParameter?: boolean;
  isGenericParameter?: boolean;
  isGenericType?: boolean;
  isGenericTypeDefinition?: boolean;
  isGenericTypeParameter?: boolean;
  isImport?: boolean;
  isInterface?: boolean;
  isLayoutSequential?: boolean;
  isMarshalByRef?: boolean;
  isNested?: boolean;
  isNestedAssembly?: boolean;
  isNestedFamANDAssem?: boolean;
  isNestedFamORAssem?: boolean;
  isNestedFamily?: boolean;
  isNestedPrivate?: boolean;
  isNestedPublic?: boolean;
  isNotPublic?: boolean;
  isPointer?: boolean;
  isPrimitive?: boolean;
  isPublic?: boolean;
  isSZArray?: boolean;
  isSealed?: boolean;
  isSecurityCritical?: boolean;
  isSecuritySafeCritical?: boolean;
  isSecurityTransparent?: boolean;
  isSerializable?: boolean;
  isSignatureType?: boolean;
  isSpecialName?: boolean;
  isTypeDefinition?: boolean;
  isUnicodeClass?: boolean;
  isValueType?: boolean;
  isVariableBoundArray?: boolean;
  isVisible?: boolean;
  memberType?: MemberTypes;
  metadataToken?: number;
  module?: Module;
  name?: null | string;
  namespace?: null | string;
  reflectedType?: Type;
  structLayoutAttribute?: StructLayoutAttribute;
  typeHandle?: RuntimeTypeHandle;
  typeInitializer?: ConstructorInfo;
  underlyingSystemType?: Type;
}
